version: '3.8'
services:
  nx-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: binod
      POSTGRES_PASSWORD: binod123
      POSTGRES_DB: db_nx
    networks:
      - my_app
networks:
  my_app:
